// Script assets have changed for v2.3.0 see
// https://help.yoyogames.com/hc/en-us/articles/360005277377 for more information
function scrFishArraySet(){
	
	
var fishNames = [
	"",
    "Lakelight",
    "Muddweller",
    "Reedripple",
    "Lakegem",
    "Weedsnout",
    "Echodepth",
    "Whisklash",
    "Bubblerise",
    "Waveshimmer",
    "Coralfin",
    "Saltysurge",
    "Tidalflicker",
    "Abyssglow",
    "Surfdrifter",
    "Finfury",
    "Lumipuff",
    "Seaspike",
    "Pearlshimmer",
    "Surgeknight",
    "Silverflicker",
    "Stormdrifter",
    "Inkfish",
    "Leafscale",
    "Timbertrickle",
    "Kelpshield",
    "Vinerider",
    "Barkbiter",
    "Fernflutter",
    "Blossomfin",
    "Pinescale",
    "Roottrickle",
    "Oakscale",
    "Blossomflutter",
    "Dracofin",
    "Fluffin",
    "Streamgill",
    "Rapidskimmer",
    "Aqualite",
    "Bouldermaw",
    "Brookflare",
    "Currentswift",
    "Mossfin",
    "Rivertwirl",
    "Pebbletrout",
    "Sunsetgill",
    "Whirlskimmer",
    "Quillure",
    "Sapphire Sturgeon",
    "Diamond Sturgeon",
    "Ruby Sturgeon",
    "Echoesolace",
    "Flyfin"
];

var fishRarity = [
    0,  // "" 
    10, // "Lakelight",
    1,  // "Muddweller",
    5,  // "Reedripple",
    10, // "Lakegem",
    1,  // "Weedsnout",
    10, // "Echodepth",
    5,  // "Whisklash",
    5,  // "Bubblerise",
    5,  // "Waveshimmer",
    10, // "Coralfin",
    10, // "Saltysurge",
    10, // "Tidalflicker",
    50, // "Abyssglow",
    5,  // "Surfdrifter",
    10, // "Finfury",
    10, // "Lumipuff",
    5,  // "Seaspike",
    10, // "Pearlshimmer",
    1,  // "Surgeknight",
    5,  // "Silverflicker",
    5,  // "Stormdrifter",
    10, // "Inkfish",
    1,  // "Leafscale",
    5,  // "Timbertrickle",
    10, // "Kelpshield",
    5,  // "Vinerider",
    1,  // "Barkbiter",
    10, // "Fernflutter",
    50, // "Blossomfin",
    5,  // "Pinescale",
    10, // "Roottrickle",
    10, // "Oakscale",
    50, // "Blossomflutter",
    50, // "Dracofin",
    50, // "Fluffin",
    1,  // "Streamgill",
    5,  // "Rapidskimmer",
    10, // "Aqualite",
    5,  // "Bouldermaw",
    10, // "Brookflare",
    10, // "Currentswift",
    5,  // "Mossfin",
    5,  // "Rivertwirl",
    1,  // "Pebbletrout",
    10, // "Sunsetgill",
    10, // "Whirlskimmer",
    50, // "Quillure",
    500, // "SapphireSturgeon",
    500, // "DiamondSturgeon",
    500, // "RubySturgeon",
    500, // "Echoesolace",
    50, // "Flyfin"
];

var fishAquaVistaInfos = [
	"",
    "The luminescent spots on this fish's body can light up dark lake waters.",
    "Known for burrowing in lake beds, this fish stirs up mud to hide from predators.",
    "It weaves through reeds with ease, its movements creating beautiful ripples on the lake surface.",
    "Its jewel-like scales are said to bring good fortune to those who find it.",
    "Known for its elongated snout, it probes through lake weed for tiny creatures.",
    "This unique species uses sound waves to navigate the dark depths of lakes.",
    "The lake's playful companion. Its whisker-like fins playfully dance through the water, bringing smiles to lakeside observers.",
    "Its playful leaps create bubbles that rise to the surface, adding charm to the tranquil waters.",
    "This fish's metallic scales refract sunlight, causing a dazzling shimmer underwater.",
    "Coral-colored scales, blend seamlessly with vibrant coral reefs in warm ocean waters.",
    "Able to withstand the harshest saltwater conditions, their scales contain salt crystals.",
    "This fish can manipulate the tidal currents to disorient predators.",
    "Found in the ocean's darkest depths, its bioluminescent glow attracts curious prey.",
    "Known for its long, slow migrations across vast oceans, powered by the waves.",
    "Swift ocean dweller. Dazzling scales, vibrant patterns race through warm waters. Often seen in tropical regions.",
    "Soft, puffy appearance, gentle glow create calming presence. Inhabits serene, clear waters.",
    "Covered in spiky scales, it uses its body to protect itself from predators.",
    "It's iridescent scales give off a pearl-like sheen, dazzling under the ocean sun.",
    "This common fish has black and silver armored scales, appearing knight-like.",
    "This silver surfer shimmers, confusing predators with its darting movements.",
    "It thrives during stormy weather, using the turbulent waves to its advantage.",
    "It is said that a book written with the ink from the inkfish will surely be a masterpiece.",
    "Found in forest streams, its scales mimic fallen leaves for camouflage.",
    "This fish inhabits water trapped in hollow trees, surviving on insects that fall in.",
    "This fish has evolved to blend perfectly into kelp forests, making it a master of hide and seek.",
    "Known to slide over moist vines during heavy rain, it spends as much time in trees as in water.",
    "Known to nibble on tree roots that hang into forest water bodies.",
    "Its fins resemble fern leaves, providing perfect camouflage in forest ponds.",
    "The fins of this fish bloom like flowers when it's ready to mate.",
    "This scary-looking has needle-like scales, blending seamlessly in pine forests.",
    "This Timbertrickle variant is found in water-filled roots of ancient trees.",
    "This Leafscale variant's oak-leaf pattern provides superior camouflage.",
    "This Fernflutter variant's flower-like fins are considered an exquisite sight.",
    "Mythical forest swimmer. Dragon-like fins allow it to glide with enchantment in mystical woodland streams.",
    "Dreamy forest drifter. Fins resemble fluff, drifts dreamily through calm, mossy streams in heart of woodlands.",
    "Streamgills have slender bodies that allow them to dart quickly between rocks. Their gills shine like gemstones under the sun.",
    "Known for its ability to dance on the water's surface, Rapidskimmer are often mistaken for water bugs.",
    "The aquatic gem. Shimmering scales emit a soothing glow, mesmerizing underwater display. Prefers clear rivers with gentle currents.",
    "With its jaw lined with rock-hard teeth, Bouldermaw can crunch through pebbles to find food.",
    "These iridescent fish create a mesmerizing light show as they leap out of the water.",
    "Its streamlined body is perfect for high-speed pursuits in fast-moving waters.",
    "Prefers slow-moving or stagnant waters and has a moss-like fin which provides camouflage.",
    "Known for its spiral movement against the current, creating miniature whirlpools.",
    "This pebbly-scaled fish is a master of camouflage in rocky riverbeds.",
    "A variant of Streamgill, Sunsetgills gleam a brilliant orange-red at dusk.",
    "Spins rapidly, creating a mesmerizing water display.",
    "Elegant quill-like fins, graceful glide enchanting presence is calm waterways.",
    "This elusive fish has sapphire scales said to have magical properties.",
    "Shimmers like a jewel in clear water. A beautiful, elusive prize testing angler skills.",
    "Glowing red like fire, its ruby scales are said to hold intense heat.",
    "This fish sings an enchanting melody, but is heard only once every hundred years.",
    "Airborne ocean marvel. Leaping from waves, gliding above water, soars alongside ocean winds with graceful aerial flips."
];

var fishInventoryInfos = [
	"",
    "Whoa, it's like a mobile lantern! So shiny...",
    "Uh oh, a fish that loves mud? Mom would go nuts.",
    "It moves so beautifully, like an underwater dancer! Poetry in motion!",
    "Look at that shine! Who needs treasure when you have this fish?",
    "What's with the long face, buddy? Or is it a nose?",
    "Now, this one's a submarine with built-in sonar. Cool and creepy...",
    "I hope someone remembers to feed my cat back home...",
    "Bubbles, bubbles everywhere! It's like a fishy jacuzzi.",
    "This one's giving off some serious disco vibes. Talk about a showstopper!",
    "Pretty in pink! Or is that coral? Either way, it's cute.",
    "Man, this fish is literally salty! Like a living, swimming salt shaker.",
    "Watch out! This one's got some serious waves. Surf's up!",
    "It's a deep-sea lightbulb! Kind of eerie, but in a cool way.",
    "Slow and steady wins the race, huh? Take your time, buddy.",
    "So fast! It's like a torpedo with scales. Yowza!",
    "Soft, glowing... it's like hugging a cloud. If clouds lived underwater...",
    "Whoa, spikey! I wouldn't want to step on this guy.",
    "Now that's what I call bling! It's like a living gemstone.",
    "Knight of the sea, huh? Looks more like an underwater tank.",
    "It's a living mirror! Reflecting all the light around. Dazzling!",
    "This one's a storm chaser. Brave little guy!",
    "A fish full of ink? Might be handy if I ever forget my pen...",
    "A fish or a leaf? Nature's got a sense of humor.",
    "Talk about a minimalist lifestyle! This one's a true survivor.",
    "Hide and seek champion right here! Where did it go?",
    "It slides on vines? That's not your average fish. That's an acrobat!",
    "A wood-eating fish! Hope it doesn't confuse my boat with food.",
    "Fern-leaf fins? That's some high-level disguise, dude!",
    "Flower fins, huh? It's like a fish and a bouquet all in one.",
    "Pineneedles on a fish? Yikes, wouldn't want to step on this guy!",
    "Lives in roots? Talk about an underground lifestyle!",
    "Oak-leaf pattern, nice! This fish knows style.",
    "Oh wow, look at those fins! Like a garden underwater.",
    "Dragon fins? More like draco-fish!",
    "Fluffy fish, how cute! It's like a water bunny.",
    "Slim and quick! This one's like an underwater snake.",
    "A fish that dances on water? Now that's a talent!",
    "A glowing gem fish, huh? Now that's fancy!",
    "Whoa, rock-hard teeth! I bet this one doesn't worry about cavities.",
    "This one's a real show-off, huh? Bet it's a hit at parties.",
    "Streamlined and fast, like a race car with fins!",
    "Camouflage game strong with this one! Can barely see it!",
    "This one's a whirlwind! Or should I say, whirlpool?",
    "Look at that, just like the riverbed! It's practically invisible.",
    "Sunset colors! This one really knows how to stand out.",
    "Whoa, it's like a spinning top, but in water!",
    "Quills on a fish? That's a first. Definitely a unique find.",
    "Sapphire scales? I bet this one's expensive.",
    "Diamond scales! Talk about an extravagant fish.",
    "It's like a fiery jewel! Absolutely stunning!",
    "A singing fish? I didn't know that was possible!",
    "Flying fish? Now I've seen everything! Talk about defying gravity."
];

var fishValue = [
  0, 1, 2, 3, 4, 5, 
  6, 7, 8, 9, 10,
  11, 12, 13, 14, 15,
  16, 17, 18, 19, 20,
  21, 22, 23, 24, 25,
  26, 27, 28, 29, 30,
  31, 32, 33, 34, 35,
  36, 37, 38, 39, 40,
  41, 42, 43, 44, 45,
  46, 47, 48, 49, 50
];

global.numberoffish = 8 //Ändra detta för varje fisk som existerar


global.fisharray[0,0] = noone

for (var i = 0; i <= global.numberoffish; ++i) {
    var fishObjName = "oFish" + string(i);
    var fishSpriteName = "sFish" + string(i);
    var fishVeganSpriteName = fishSpriteName + "_vegan";
	
	global.fisharray[i, 0] = asset_get_index(fishObjName); // Object
    global.fisharray[i, 1] = asset_get_index(fishSpriteName); // Sprite
    global.fisharray[i, 2] = asset_get_index(fishVeganSpriteName); // Vegan Sprite
	global.fisharray[i, 3] = fishValue[i]; // Cost in store
    global.fisharray[i, 4] = fishNames[i]; // Fish name
    global.fisharray[i, 5] = fishAquaVistaInfos[i]; // AquaVista info
    global.fisharray[i, 6] = fishInventoryInfos[i]; // Inventory info
    global.fisharray[i, 7] = sprite_get_xoffset(asset_get_index(fishSpriteName)); // Sprite origin X, normal fish
    global.fisharray[i, 8] = sprite_get_yoffset(asset_get_index(fishSpriteName)); // Sprite origin Y, normal fish
    global.fisharray[i, 9] = sprite_get_xoffset(asset_get_index(fishVeganSpriteName)); // Sprite origin X, vegan
    global.fisharray[i, 10] = sprite_get_yoffset(asset_get_index(fishVeganSpriteName)); // Sprite origin Y, vegan
	global.fisharray[i, 11] = fishRarity[i];
}
}