//scrInventoryAdd(oKeyInventory,enumItem.Shovel)
//scrInventoryAdd(oKeyInventory,enumItem.Bark)
//scrInventoryAdd(oKeyInventory,enumItem.Bunnyhouse)
//scrInventoryAdd(oKeyInventory,enumItem.Driftwood)
//scrInventoryAdd(oKeyInventory,enumItem.Coal)
//scrInventoryAdd(oKeyInventory,enumItem.Bark)
